-- ============================================================
-- Milestone 2 - Task 4: Database Logging & Analytics Queries
-- Author: Pragathi (Database Architect) - Team 4
-- Branch: pragathi/week2-milestone2
--
-- These queries persist the results returned by Chinmayee's
-- POST /api/ai/evaluate endpoint, and the Speed Quiz results
-- from Ankur's Speed Quiz screen.
-- ============================================================

-- ------------------------------------------------------------
-- Query 1: Save each practice session result into Practice_History
-- Called right after the frontend receives a response from
-- POST /api/ai/evaluate.
-- ------------------------------------------------------------
INSERT INTO Practice_History (
    learner_id,
    sign_name,
    predicted_sign,
    accuracy_score,
    is_correct,
    duration_seconds,
    session_id,
    status
)
VALUES (
    ?,              -- learner_id: current logged-in learner
    ?,              -- sign_name: target sign selected by learner
    ?,              -- predicted_sign: from API response
    ?,              -- accuracy_score: from API's accuracy_percentage
    ?,              -- is_correct: from API's is_correct
    ?,              -- duration_seconds: usually 10 seconds
    ?,              -- session_id: from frontend
    CASE WHEN ? = TRUE THEN 'Completed' ELSE 'Failed' END   -- status derived from is_correct
);


-- ------------------------------------------------------------
-- Query 2: Update the skill mastery percentage for a learner
-- after they practice a sign/module.
-- Mastery = average of recent accuracy_score values for the
-- same learner + sign, from Practice_History.
-- ------------------------------------------------------------
INSERT INTO Skill_Mastery (learner_id, sign_name, accuracy_score, mastery_percentage, status)
SELECT
    ?  AS learner_id,                                   -- current learner_id
    ?  AS sign_name,                                     -- sign just practiced
    ?  AS accuracy_score,                                 -- latest accuracy_score
    avg_accuracy.mastery_percentage,
    CASE
        WHEN avg_accuracy.mastery_percentage >= 80 THEN 'Mastered'
        WHEN avg_accuracy.mastery_percentage >= 50 THEN 'In Progress'
        ELSE 'Needs Practice'
    END AS status
FROM (
    SELECT AVG(accuracy_score) AS mastery_percentage
    FROM Practice_History
    WHERE learner_id = ?          -- current learner_id
      AND sign_name  = ?          -- sign just practiced
) AS avg_accuracy
ON DUPLICATE KEY UPDATE
    accuracy_score     = VALUES(accuracy_score),
    mastery_percentage = VALUES(mastery_percentage),
    status              = VALUES(status);

-- Note: ON DUPLICATE KEY UPDATE requires a UNIQUE constraint on
-- (learner_id, sign_name) in Skill_Mastery. If that constraint
-- doesn't exist yet, use this simpler two-step version instead:
--
-- UPDATE Skill_Mastery
-- SET mastery_percentage = (
--         SELECT AVG(accuracy_score) FROM Practice_History
--         WHERE learner_id = ? AND sign_name = ?
--     ),
--     status = CASE
--         WHEN mastery_percentage >= 80 THEN 'Mastered'
--         WHEN mastery_percentage >= 50 THEN 'In Progress'
--         ELSE 'Needs Practice'
--     END
-- WHERE learner_id = ? AND sign_name = ?;


-- ------------------------------------------------------------
-- Query 3: Save AI feedback and corrections from the gesture
-- evaluation endpoint into AI_Practice_Feedback.
-- Run right after Query 1 inserts the Practice_History row,
-- using that new practice_id.
-- ------------------------------------------------------------
INSERT INTO AI_Practice_Feedback (
    learner_id,
    practice_id,
    sign_name,
    predicted_sign,
    accuracy_percentage,
    corrections
)
VALUES (
    ?,              -- learner_id
    ?,              -- practice_id: the ID just generated by Query 1
    ?,              -- sign_name
    ?,              -- predicted_sign
    ?,              -- accuracy_percentage
    ?               -- corrections: JSON/text list, e.g. '["Hand angle optimal","Good thumb position"]'
);


-- ------------------------------------------------------------
-- Query 4: Update/insert quiz score after the learner completes
-- the 60-second Speed Quiz.
-- ------------------------------------------------------------
INSERT INTO Quiz_Scores (
    learner_id,
    session_id,
    total_questions,
    correct_answers,
    score_percentage,
    duration_seconds
)
VALUES (
    ?,              -- learner_id
    ?,              -- session_id / quiz_id from frontend
    ?,              -- total_questions
    ?,              -- correct_answers
    ?,              -- score_percentage: (correct_answers / total_questions) * 100
    60              -- duration_seconds: fixed 60s Speed Quiz
);